// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://igxivnwtpaneagmqsggk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlneGl2bnd0cGFuZWFnbXFzZ2drIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUwNDQ3OTIsImV4cCI6MjA3MDYyMDc5Mn0.xEZSEwENr6KoLEAN7WFyujNWmX7Nylbq09rO4Ob4ufA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});